var student = require('../models/students.js'),
	modules = require('../models/modules.js'),
	httpRequest = require('request'),
	auth_config = require('../config/auth.js');

exports.refreshStudentModules = function (req, res) {
	/*
		@params : 
			studentId : Matric. number of the student
			authToken : Auth Token generated by user login on client UI
		
		@returns :
			status : Status message of the 
	*/

	//Get parameter values
	var studentId = args.studentId,
		authToken = args.authToken;

	//Prepare message to be returned
	var statusMessage = null;

	//Create Module Info Retrieval url
	var getModulesUrl = "https://ivle.nus.edu.sg/api/Lapi.svc/Modules_Taken?APIKey="+
		auth_config.lapiKey+"&AuthToken="+authToken+"&StudentID="+studentId;
};


